version: '2'
services:
  verticle:
    build: ./
    ports:
      - 8080:8080
    links:
      - mongo
    network_mode: bridge
    environment:
      - env_file=env_docker.json

  mongo:
    image: tutum/mongodb
    network_mode: bridge
    expose:
      - "27017"
    environment:
      - AUTH=no
